[package]
name = "pixel_world"
version.workspace = true
edition.workspace = true
description = "Infinite cellular automata simulation plugin for Bevy"

[dependencies]
bevy = { workspace = true }
ab_glyph = "0.2"
fastnoise2 = "0.4"
